<section class="ftco-section">
  <div class="container">
    <a href="/admin/uj-etel-letrehozasa">
      <button class="btn btn-outline-success mb-4">Új létrehozása</button>
    </a>
    <div class="row">
      <div class="col-md-12">
      <?php foreach($params['dishList'] as $dishTypes) : ?> 
      <div class="row mb-3">
        <h1><?= $dishTypes['name'] ?></h1>
      </div>
      <?php foreach($dishTypes['dishes'] as $dishList) : ?>
        <div class="row mb-3">
          <div class="pricing-entry d-flex mr-2 ml-2 pt-2 pb-2<?= $dishList['isActive'] === 0 ? ' border rounded border-danger border-style-dotted' : '' ?>">
            <div class="desc pl-3">
              <div class="d-flex text align-items-center">
                <h3><span><?= $dishList['name'] ?></span></h3>
                <span class="price"><?= $dishList['price'] ?> Ft</span>
              </div>
              <div class="d-block">
                <p><?= $dishList['description'] ?></p>
              </div>
              <?php if($dishList['isActive'] === 0) : ?>
              <span class="text-danger float-right pl-2 pr-2">
                Inaktív
              </span>
              <?php endif ?>
              <a href="/admin/etel-szerkesztese/<?= $dishList['slug'] ?>">
                <button class="btn btn-sm btn-outline-warning">Szerkesztés</button>
              </a>
              <form action="/delete-dish/<?= $dishList['id'] ?>" method="POST" class="d-inline-block">
                <button class="btn btn-sm btn-outline-danger">Törlés</button>
              </form>
            </div>
          </div>
        </div>
        <?php endforeach ?>
        <?php endforeach ?>
      </div>
    </div>
  </div>
</section>