<!DOCTYPE html>
<html lang="en">

<head>
  <title>Kódbázis Étterem</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:400,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Great+Vibes" rel="stylesheet">
  <link rel="stylesheet" href="/public/css/open-iconic-bootstrap.min.css">
  <link rel="stylesheet" href="/public/css/owl.carousel.min.css">
  <link rel="stylesheet" href="/public/css/owl.theme.default.min.css">
  <link rel="stylesheet" href="/public/css/magnific-popup.css">
  <link rel="stylesheet" href="/public/css/animate.css">
  <link rel="stylesheet" href="/public/css/aos.css">
  <link rel="stylesheet" href="/public/css/ionicons.min.css">
  <link rel="stylesheet" href="/public/css/bootstrap-datepicker.css">
  <link rel="stylesheet" href="/public/css/jquery.timepicker.css">
  <link rel="stylesheet" href="/public/css/flaticon.css">
  <link rel="stylesheet" href="/public/css/icomoon.css">
  <link rel="stylesheet" href="/public/css/style.css">
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
      <a class="navbar-brand" href="/">Kódbázis
        <small>Étterem</small>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="oi oi-menu"></span> Menu
      </button>
      <div class="collapse navbar-collapse" id="ftco-nav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item"><a href="/admin" class="nav-link">Admin</a></li>
        </ul>
      </div>
    </div>
  </nav>

  <section class="ftco-section">
    <?= $params['content'] ?? '' ?>
  </section>

  <footer class="ftco-footer ftco-section img">
    <div class="overlay"></div>
    <div class="container">
      <div class="row mb-5">
        <div class="col-lg-3 col-md-6 mb-5 mb-md-5">
          <div class="ftco-footer-widget mb-4">
            <h2 class="ftco-heading-2">Rólunk</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis nisi felis, egestas in ultricies a, venenatis ut enim.</p>
            <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
              <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
              <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
              <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
            </ul>
          </div>
        </div>

        <div class="col-lg-2 col-md-6 mb-5 mb-md-5">
          <div class="ftco-footer-widget mb-4 ml-md-4">
            <h2 class="ftco-heading-2">Szolgáltatások</h2>
            <ul class="list-unstyled">
              <li><a href="#" class="py-2 d-block">Kiszállítás</a></li>
              <li><a href="#" class="py-2 d-block">ÁSZF</a></li>
              <li><a href="#" class="py-2 d-block">Elérhetőség</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 text-center">

          <p>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            Copyright &copy;2021
            All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
          </p>
        </div>
      </div>
    </div>
  </footer>
  <div id="ftco-loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
      <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" />
      <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00" />
    </svg>
  </div>
  <script src="/public/js/jquery.min.js"></script>
  <script src="/public/js/jquery-migrate-3.0.1.min.js"></script>
  <script src="/public/js/popper.min.js"></script>
  <script src="/public/js/bootstrap.min.js"></script>
  <script src="/public/js/jquery.easing.1.3.js"></script>
  <script src="/public/js/jquery.waypoints.min.js"></script>
  <script src="/public/js/jquery.stellar.min.js"></script>
  <script src="/public/js/owl.carousel.min.js"></script>
  <script src="/public/js/jquery.magnific-popup.min.js"></script>
  <script src="/public/js/aos.js"></script>
  <script src="/public/js/jquery.animateNumber.min.js"></script>
  <script src="/public/js/bootstrap-datepicker.js"></script>
  <script src="/public/js/jquery.timepicker.min.js"></script>
  <script src="/public/js/scrollax.min.js"></script>
  <script src="/public/js/main.js"></script>

</body>

</html>